import type { Frame, LocalizedText } from '@/models';
const L = (en: string, zh: string, es: string): LocalizedText => ({ 'en-US': en, 'zh-CN': zh, 'es-US': es });
/** Mock catalog. Swap `list()` implementation for REST later without touching screens. */
const CATALOG: Frame[] = [
  { id:'arashiyama', sku:'KY-AR-001', slug:'arashiyama', collectionName:'Arashiyama', nameZH:'岚山',
    name:L('Arashiyama','岚山','Arashiyama'), price:95, category:'optical', frameShape:'round',
    frameMaterial:L('Acetate','板材','Acetato'),
    colors:[{key:'night',hex:'#0D1B2A',name:L('Night','夜空蓝','Noche')},{key:'tortoise',hex:'#8B5A2B',name:L('Tortoise','玳瑁','Carey')},{key:'sakura',hex:'#FF4F8B',name:L('Sakura','樱花粉','Sakura')},{key:'teal',hex:'#0B7C6E',name:L('Teal','山水青','Verde azulado')}],
    sizes:[{key:'S',lensWidth:46,bridge:19,temple:140},{key:'M',lensWidth:49,bridge:20,temple:145},{key:'L',lensWidth:52,bridge:21,temple:150}], defaultSize:'M',
    art:'round', tint:'tint-sakura',
    fit:L('Medium fit · suits oval, round and square faces. The keyhole bridge sits comfortably on low-to-medium nose bridges.','中号版型 · 适合鹅蛋脸、圆脸与方脸。锁孔鼻梁对低中鼻梁也很友好。','Ajuste medio · va bien con rostros ovalados, redondos y cuadrados. El puente tipo keyhole es cómodo para puentes nasales bajos y medios.'),
    description:L('Italian acetate, vintage round silhouette.','意大利板材,复古圆框。','Acetato italiano, silueta redonda vintage.'),
    prescriptionCompatible:true, rxRange:'SPH −10.00 to +6.00 · CYL to −4.00',
    availableLensMaterials:['std150','poly','hi160','hi167','hi174'],
    tags:['bestseller'], inventoryStatus:'in_stock', bestSeller:true, featured:true, fsaEligible:true, rating:4.8, reviewCount:128 },
  { id:'gion', sku:'KY-GI-002', slug:'gion', collectionName:'Gion', nameZH:'祇园',
    name:L('Gion','祇园','Gion'), price:135, category:'optical', frameShape:'square',
    frameMaterial:L('Titanium','纯钛','Titanio'),
    colors:[{key:'gunmetal',hex:'#444444',name:L('Gunmetal','枪灰','Gris metálico')},{key:'silver',hex:'#B8B8B8',name:L('Silver','银','Plata')},{key:'gold',hex:'#FFC83D',name:L('Gold','金','Dorado')}],
    sizes:[{key:'M',lensWidth:51,bridge:18,temple:145},{key:'L',lensWidth:54,bridge:19,temple:150}], defaultSize:'M',
    art:'square', tint:'tint-teal',
    fit:L('Pure titanium at just 11g — all-day comfort.','纯钛仅 11g,整天佩戴无压感。','Titanio puro de solo 11 g — comodidad todo el día.'),
    description:L('Pure titanium, square silhouette.','纯钛方框。','Titanio puro, silueta cuadrada.'),
    prescriptionCompatible:true, rxRange:'SPH −10.00 to +6.00 · CYL to −4.00',
    availableLensMaterials:['std150','poly','hi160','hi167','hi174'],
    tags:[], inventoryStatus:'in_stock', fsaEligible:true, rating:4.7, reviewCount:86 },
  { id:'tsukimi', sku:'KY-TS-003', slug:'tsukimi', collectionName:'Tsukimi', nameZH:'月见',
    name:L('Tsukimi','月见','Tsukimi'), price:110, category:'optical', frameShape:'cat-eye',
    frameMaterial:L('Acetate','板材','Acetato'),
    colors:[{key:'amber',hex:'#8B5A2B',name:L('Amber','琥珀','Ámbar')},{key:'night',hex:'#0D1B2A',name:L('Night','夜空蓝','Noche')},{key:'sunset',hex:'#FF6A3D',name:L('Sunset','日出橙','Atardecer')}],
    sizes:[{key:'S',lensWidth:47,bridge:19,temple:140},{key:'M',lensWidth:50,bridge:20,temple:145}], defaultSize:'M',
    art:'cat', tint:'tint-gold',
    fit:L('Upswept lines with subtle lift for any face shape.','上扬线条,修饰任何脸型。','Líneas elevadas que favorecen cualquier rostro.'),
    description:L('Cat-eye with amber tortoise finish.','琥珀玳瑁猫眼框。','Cat-eye con acabado carey ámbar.'),
    prescriptionCompatible:true, rxRange:'SPH −10.00 to +6.00 · CYL to −4.00',
    availableLensMaterials:['std150','poly','hi160','hi167','hi174'],
    tags:['new'], inventoryStatus:'in_stock', newArrival:true, fsaEligible:true, rating:4.9, reviewCount:42 },
  { id:'tasogare', sku:'KY-TA-004', slug:'tasogare', collectionName:'Tasogare', nameZH:'黄昏',
    name:L('Tasogare','黄昏','Tasogare'), price:85, category:'sun', frameShape:'square',
    frameMaterial:L('Acetate','板材','Acetato'),
    colors:[{key:'night',hex:'#0D1B2A',name:L('Night','夜空蓝','Noche')},{key:'havana',hex:'#5A3E2B',name:L('Havana','哈瓦那棕','Habana')}],
    sizes:[{key:'M',lensWidth:52,bridge:20,temple:145}], defaultSize:'M',
    art:'sun', tint:'tint-sunrise',
    fit:L('UV400 polarized-ready. Built for road trips and beach days.','UV400,开车与海边通用。','Listas para polarizado UV400. Para viajes y días de playa.'),
    description:L('Classic shades, UV400.','经典墨镜,UV400。','Gafas clásicas, UV400.'),
    prescriptionCompatible:true, rxRange:'SPH −8.00 to +4.00',
    availableLensMaterials:['std150','poly','hi160','hi167'],
    tags:[], inventoryStatus:'in_stock', fsaEligible:true, rating:4.6, reviewCount:64 },
  { id:'kamo', sku:'KY-KA-005', slug:'kamo', collectionName:'Kamo', nameZH:'鸭川',
    name:L('Kamo','鸭川','Kamo'), price:120, category:'optical', frameShape:'round',
    frameMaterial:L('Titanium','纯钛','Titanio'),
    colors:[{key:'teal',hex:'#0B7C6E',name:L('Teal','山水青','Verde azulado')},{key:'gunmetal',hex:'#444444',name:L('Gunmetal','枪灰','Gris metálico')}],
    sizes:[{key:'S',lensWidth:46,bridge:20,temple:140},{key:'M',lensWidth:49,bridge:21,temple:145}], defaultSize:'M',
    art:'round', tint:'tint-teal',
    fit:L('Slim round titanium with adjustable nose pads.','细圆钛框,可调鼻托。','Titanio redondo delgado con plaquetas ajustables.'),
    description:L('Slim round titanium.','细圆钛框。','Titanio redondo delgado.'),
    prescriptionCompatible:true, rxRange:'SPH −10.00 to +6.00 · CYL to −4.00',
    availableLensMaterials:['std150','poly','hi160','hi167','hi174'],
    tags:['new'], inventoryStatus:'in_stock', newArrival:true, fsaEligible:true, rating:4.7, reviewCount:31 },
  { id:'fushimi', sku:'KY-FU-006', slug:'fushimi', collectionName:'Fushimi', nameZH:'伏见',
    name:L('Fushimi','伏见','Fushimi'), price:98, category:'sun', frameShape:'aviator',
    frameMaterial:L('Metal','金属','Metal'),
    colors:[{key:'gold',hex:'#FFC83D',name:L('Gold','金','Dorado')},{key:'silver',hex:'#B8B8B8',name:L('Silver','银','Plata')}],
    sizes:[{key:'M',lensWidth:52,bridge:19,temple:145}], defaultSize:'M',
    art:'aviator', tint:'tint-gold',
    fit:L('Gold metal aviator with gradient amber lenses.','金色飞行员框,渐变茶色镜片。','Aviador dorado con lentes ámbar degradados.'),
    description:L('Gold aviator sunglasses.','金色飞行员太阳镜。','Gafas de sol aviador doradas.'),
    prescriptionCompatible:true, rxRange:'SPH −8.00 to +4.00',
    availableLensMaterials:['std150','poly','hi160','hi167'],
    tags:['new'], inventoryStatus:'in_stock', newArrival:true, fsaEligible:true, rating:4.5, reviewCount:23 },
];
export const ProductService = {
  async list(): Promise<Frame[]> { return CATALOG; },
  async byId(id: string): Promise<Frame | undefined> { return CATALOG.find(f => f.id === id); },
};
