import type { LensMaterial } from '@/models';
/** Catalog is configuration-driven; later replaceable by backend. Bands: 0 ≤±2 · 1 ±2–4 · 2 ±4–6 · 3 >±6 · 4 unsure */
export const LENS_MATERIALS: LensMaterial[] = [
  { id:'std150', index:1.5, material:'cr39',
    name:{'en-US':'Standard 1.50','zh-CN':'标准 1.50','es-US':'Estándar 1.50'},
    label:{'en-US':'Standard','zh-CN':'标准','es-US':'Estándar'},
    description:{'en-US':'Good everyday lens for eligible lighter prescriptions.','zh-CN':'适合较低度数的日常镜片。','es-US':'Buen lente para uso diario con graduaciones ligeras.'},
    price:0, thicknessRating:4, weightRating:2, impactResistance:'standard',
    recommendedRange:'±0 – ±2.00', compatibleStrengthBands:[0,4], badges:[], enabled:true },
  { id:'poly', index:null, material:'polycarbonate',
    name:{'en-US':'Polycarbonate','zh-CN':'PC 聚碳酸酯','es-US':'Policarbonato'},
    label:{'en-US':'Lightweight + Impact Resistant','zh-CN':'轻量 + 抗冲击','es-US':'Ligero + Resistente a impactos'},
    description:{'en-US':'Lightweight and highly impact-resistant. A great choice for active lifestyles and added durability.','zh-CN':'轻盈且抗冲击性极强,适合运动活跃人群与追求耐用者。','es-US':'Ligero y muy resistente a impactos. Ideal para estilos de vida activos y mayor durabilidad.'},
    price:35, thicknessRating:3, weightRating:0, impactResistance:'high',
    recommendedRange:'±0 – ±6.00', compatibleStrengthBands:[0,1,2,4], badges:['impact','light'], enabled:true },
  { id:'hi160', index:1.6, material:'high-index',
    name:{'en-US':'Thin 1.60','zh-CN':'薄 1.60','es-US':'Delgado 1.60'},
    label:{'en-US':'Thin','zh-CN':'薄','es-US':'Delgado'},
    description:{'en-US':'Thinner profile for moderate prescriptions.','zh-CN':'中等度数的更薄选择。','es-US':'Perfil más delgado para graduaciones moderadas.'},
    price:30, thicknessRating:3, weightRating:1, impactResistance:'standard',
    recommendedRange:'±2.00 – ±4.00', compatibleStrengthBands:[0,1,2,3,4], badges:[], enabled:true },
  { id:'hi167', index:1.67, material:'high-index',
    name:{'en-US':'Thinner 1.67','zh-CN':'更薄 1.67','es-US':'Más delgado 1.67'},
    label:{'en-US':'Extra Thin','zh-CN':'超薄','es-US':'Extra delgado'},
    description:{'en-US':'Designed for stronger prescriptions.','zh-CN':'为较高度数设计。','es-US':'Diseñado para graduaciones más fuertes.'},
    price:65, thicknessRating:2, weightRating:1, impactResistance:'standard',
    recommendedRange:'±4.00 – ±6.00', compatibleStrengthBands:[0,1,2,3,4], badges:[], enabled:true },
  { id:'hi174', index:1.74, material:'high-index',
    name:{'en-US':'Thinnest 1.74','zh-CN':'最薄 1.74','es-US':'El más delgado 1.74'},
    label:{'en-US':'Ultra Thin','zh-CN':'极薄','es-US':'Ultra delgado'},
    description:{'en-US':'Our thinnest lens option for eligible strong prescriptions.','zh-CN':'我们最薄的镜片,适合符合条件的高度数。','es-US':'Nuestro lente más delgado para graduaciones fuertes elegibles.'},
    price:110, thicknessRating:1, weightRating:1, impactResistance:'standard',
    recommendedRange:'±6.00 +', compatibleStrengthBands:[1,2,3,4], badges:[], enabled:true },
];
