import type { LensMaterial } from '@/models';
/** Catalog is configuration-driven; later replaceable by backend. Bands: 0 ≤±2 · 1 ±2–±4.5 · 2 ±4.5–±6 · 3 >±6 · 4 unsure */
export const LENS_MATERIALS: LensMaterial[] = [
  { id:'std150', index:1.5, material:'cr39',
    name:{'en-US':'Standard 1.50','zh-CN':'标准 1.50','es-US':'Estándar 1.50'},
    label:{'en-US':'Standard','zh-CN':'标准','es-US':'Estándar'},
    description:{'en-US':'Everyday standard lens.','zh-CN':'日常标准镜片。','es-US':'Lente estándar para uso diario.'},
    price:0, thicknessRating:4, weightRating:2, impactResistance:'standard',
    recommendedRange:'±0 – ±4.50', compatibleStrengthBands:[0,1,4], badges:[], enabled:true },
  { id:'poly', index:null, material:'polycarbonate',
    name:{'en-US':'Polycarbonate','zh-CN':'PC 聚碳酸酯','es-US':'Policarbonato'},
    label:{'en-US':'Lightweight + Impact Resistant','zh-CN':'轻量 + 抗冲击','es-US':'Ligero + Resistente a impactos'},
    description:{'en-US':'Lightweight and highly impact-resistant. A great choice for active lifestyles, sports, and kids & teens where durability matters most.','zh-CN':'轻盈且抗冲击性极强,适合运动活跃人群、儿童与青少年,以及一切看重耐用的场景。','es-US':'Ligero y muy resistente a impactos. Ideal para estilos de vida activos, deporte y para niños y adolescentes donde la durabilidad es lo más importante.'},
    price:35, thicknessRating:3, weightRating:0, impactResistance:'high',
    recommendedRange:'±0 – ±6.00', compatibleStrengthBands:[0,1,2,4], badges:['impact','light'], enabled:true },
  { id:'hi160', index:1.6, material:'high-index',
    name:{'en-US':'1.60 High Index','zh-CN':'1.60 高折射率','es-US':'1.60 Alto índice'},
    label:{'en-US':'Thin','zh-CN':'薄','es-US':'Delgado'},
    description:{'en-US':'Thinner and lighter than standard.','zh-CN':'比标准镜片更薄更轻。','es-US':'Más delgado y ligero que el estándar.'},
    price:30, thicknessRating:3, weightRating:1, impactResistance:'standard',
    recommendedRange:'±2.00 – ±4.00', compatibleStrengthBands:[0,1,2,3,4], badges:[], enabled:true },
  { id:'hi167', index:1.67, material:'high-index',
    name:{'en-US':'1.67 High Index','zh-CN':'1.67 高折射率','es-US':'1.67 Alto índice'},
    label:{'en-US':'Extra Thin','zh-CN':'超薄','es-US':'Extra delgado'},
    description:{'en-US':'Extra thin for stronger prescriptions.','zh-CN':'更高度数的超薄选择。','es-US':'Extra delgado para graduaciones más fuertes.'},
    price:65, thicknessRating:2, weightRating:1, impactResistance:'standard',
    recommendedRange:'±4.00 – ±6.00', compatibleStrengthBands:[0,1,2,3,4], badges:[], enabled:true },
  { id:'hi174', index:1.74, material:'high-index',
    name:{'en-US':'1.74 High Index','zh-CN':'1.74 高折射率','es-US':'1.74 Alto índice'},
    label:{'en-US':'Ultra Thin','zh-CN':'极薄','es-US':'Ultra delgado'},
    description:{'en-US':'Thinnest option for high prescriptions.','zh-CN':'高度数的最薄选择。','es-US':'La opción más delgada para graduaciones altas.'},
    price:110, thicknessRating:1, weightRating:1, impactResistance:'standard',
    recommendedRange:'±6.00 +', compatibleStrengthBands:[1,2,3,4], badges:[], enabled:true },
];
